# Generated by Django 4.2.2 on 2023-06-27 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=124)),
                ("description", models.CharField(default="", max_length=512)),
                ("estimate_time", models.TimeField(default="00:00:00")),
                (
                    "pct_total_time",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "nb_days_affected",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                (
                    "nb_hours_on_project",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                (
                    "nb_hours_affected",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                ("estimate_start_date", models.DateField()),
                ("estimate_end_date", models.DateField()),
                ("real_start_date", models.DateField()),
                ("real_end_date", models.DateField()),
                ("real_time", models.TimeField(default="00:00:00")),
                ("real_time_on_project", models.TimeField(default="00:00:00")),
                ("evaluate_date", models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_project"
            ),
        ),
    ]
