# Generated by Django 4.2.2 on 2023-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="nb_hours_affected",
        ),
        migrations.RemoveField(
            model_name="project",
            name="nb_hours_on_project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="pct_total_time",
        ),
        migrations.AddField(
            model_name="project",
            name="subject",
            field=models.CharField(default="Projet ??", max_length=124),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("subject",), name="unique_project"
            ),
        ),
    ]
