# Generated by Django 4.2.2 on 2023-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0002_remove_project_unique_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="estimate_time",
            field=models.DurationField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time",
            field=models.DurationField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time_on_project",
            field=models.DurationField(default="00:00:00"),
        ),
    ]
