# Generated by Django 4.2.2 on 2023-06-27 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0004_project_estimate_time_old_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="estimate_time_old",
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time_on_project",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
