# Generated by Django 4.2.2 on 2023-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0005_remove_project_estimate_time_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="estimate_time",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time_on_project",
            field=models.DurationField(),
        ),
    ]
