# Generated by Django 4.2.2 on 2023-06-28 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0006_alter_project_estimate_time_alter_project_real_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="estimate_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="project",
            name="real_time_on_project",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_task", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ORG", "Organisation"),
                            ("FRM", "Forum"),
                            ("MEN", "Mentorat"),
                            ("DEV", "Developpement"),
                            ("FOR", "Formation"),
                            ("EVL", "Evaluation"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("description", models.CharField(default="", max_length=512)),
                ("estimate_time", models.DurationField(default=datetime.timedelta(0))),
                ("real_time", models.DurationField(default=datetime.timedelta(0))),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_task",
                        to="graphs.project",
                    ),
                ),
            ],
        ),
    ]
